sudo: false

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - libhdf5-serial-dev

matrix:
    include:
      - os: linux
        language: python
      - os: osx
        language: generic

before_install:
  - export PATH=$PATH:~/.local/bin:~/bin
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install homebrew/science/hdf5; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sudo pip install -U numpy pytest; fi

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then python setup.py install; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sudo python setup.py install; fi

script:
  - py.test --version #dummy

